### PR TITLE
[WIP] Add disqus integration

### PR DESCRIPTION
**Pull request by fosskers**
This was originally done by @asabaya3 .

### CODE REVIEW

**Comment by fosskers** [comment]
@asabaya3 is the remaining config just the area in the comments?

**Comment by asabaya3** [comment]
@fosskers Any references to sfucsss.disqus.com can be changed to your disqus link. sfucsss is a disqus site (I guess not sure how it's called) I created and have control over. I can give other people admin access or potentially hand over ownership. I was just wondering if you already had an account or something setup with disqus.

**Comment by fosskers** [comment]
I don't have any account info for one, so I'm going to assume no.

**Comment by asabaya3** [comment]
So how do you want to handle disqus management?

**Comment by fosskers** [comment]
I'll get the credentials from you for the site you made, and then add that to the JS.

**Comment by fosskers** [comment]
The comments number on the main page seems static. It doesn't move from 0, even if I make a test comment.

**Pull request merged**
