### PR TITLE
Linux / Windows difference fixes

### PR DESCRIPTION
**Pull request by fosskers**
- This was causing a "No template found" error.
  I suspect this is a Linux/Windows issue?

### CODE REVIEW

**Comment by fosskers** [comment]
I'd like to know what @asabaya3 thinks about this.

**Comment by asabaya3** [comment]
Probably a Windows/Linux thing. Should be fine to merge it in.

**Comment by fosskers** [comment]
Would this break your dev environment? Are you on windows?

**Comment by asabaya3** [comment]
:+1:  No, I should be fine. Windows can take both slashes. I don't really pay attention to what facing the slashes normally are. Didn't even realize Linux( and the rest of the world, like in urls) use / instead of . I'll keep that in mind from now on.

**Pull request merged**
